version: '1'

services:
  database:
    container_name: voca_db
    image: mysql/mysql-server:8.0.32
    environment:
      MYSQL_DATABASE: voca_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "13306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - voca-network

  application:
    container_name: voca-main-server
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://voca_db:3306/voca_db
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - voca-network

networks:
  voca-network:
    driver: bridge